name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
    push:
      branches: [ master ]
#   pull_request:
#     branches: [ master ]
jobs:
  build:
    name: Build Windows Zip
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: '16.x'
        distribution: zulu
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build windows
    - uses: actions/upload-artifact@v3
      with:
        # Name of the command/step.
        name: Windows Zip
        path: build/windows/runner/Release/
#       uses: ncipollo/release-action@v1
#       with:
#            tag: "latest"
#            artifacts: "build/app/outputs/apk/debug/*.exe"
#            token: $